version: '3.8'

services:
  demo-integration:
    image: "demo-integration-sidecar:latest"
    container_name: "app-integration"
    ports:
      - "8080:8080"
      - "3500:3500"
    environment:
      SPRING_PROFILES_ACTIVE: docker  # Active le profil "docker" dans l'application
    volumes:
      - ./src/main/resources/docker/myapp.jar:/app/myapp.jar
      - ./src/main/resources/input:/app/input
    depends_on:
      - kafka
      - postgres

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - kafka-net
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  akhq:
    image: tchiotludo/akhq
    container_name: akhq
    ports:
      - "9090:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
              schema-registry:
                url: "http://schema-registry:8085"
              connect:
                - name: "connect"
                  url: "http://connect:8083"
    networks:
      - kafka-net

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"  # Port d'écoute de PostgreSQL
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: demo
    networks:
      - pg-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    ports:
      - "5050:80"  # Port pour accéder à pgAdmin depuis le navigateur
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"  # Adresse e-mail par défaut pour l'authentification
      PGADMIN_DEFAULT_PASSWORD: "admin"  # Mot de passe par défaut pour l'authentification
    networks:
      - pg-net

networks:
  kafka-net:
    driver: bridge
  pg-net:
    driver: bridge