apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
spec:
  type: pubsub.kafka
  metadata:
    - name: brokers
      value: "localhost:9092"  # Adresse et port du ou des brokers Kafka
    - name: authType
      value: "none"  # Type d'authentification (none, sasl, etc.)
    - name: version
      value: "2.0.0"  # Version de Kafka
