apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
spec:
  type: pubsub.kafka
  metadata:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
    - name: brokers
      value: "localhost:9092"  # Adresse du broker Kafka (défini dans la variable KAFKA_ADVERTISED_LISTENERS PLAINTEXT_HOST://)
    - name: authType
      value: "none"  # Type d'authentification (none, sasl, etc.)
    - name: version
      value: "2.0.0"  # Version de Kafka
